import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import {
  GetKpisResponse,
  GetProductsResponse,
  GetTransactionsResponse,
  LoginResponse,
  RegisterResponse,
  LoginRequest,
  RegisterRequest,
} from "./types";

// Creates an API instance using createApi function
export const api = createApi({
  /**
   * Set up base query with base URL
   * Specify the path for the API slice in the Redux store
   * Define tag types for caching
   */
  baseQuery: fetchBaseQuery({ baseUrl: import.meta.env.VITE_BASE_URL }),
  reducerPath: "main",
  tagTypes: ["Kpis", "Products", "Transactions", "User"],
  endpoints: (build) => ({
    // Define endpoints for various API requests
    getKpis: build.query<Array<GetKpisResponse>, void>({
      /**
       * Query to fetch KPIs data
       * Endpoint URL
       * tags for caching
       */
      query: () => "kpi/kpis/",
      providesTags: ["Kpis"],
    }),
    getProducts: build.query<Array<GetProductsResponse>, void>({
      /**
       * Query to fetch products data
       * Endpoint URL
       * tag for caching
       */
      query: () => "product/products/",
      providesTags: ["Products"],
    }),
    getTransactions: build.query<Array<GetTransactionsResponse>, void>({
      /**
       * Query to fetch transactions data
       * Endpoint URL
       * tag for caching
       */
      query: () => "transaction/transactions/",
      providesTags: ["Transactions"],
    }),
    login: build.mutation<LoginResponse, LoginRequest>({
      query: (credentials) => ({
        /**
         * Defines https request details
         * endpoint URL
         * HTTP method
         * Request body contains
         */
        url: "auth/login",
        method: "POST",
        body: credentials,
      }),
      invalidatesTags: ["User"], // Invalidate "User" tag type after login
    }),
    register: build.mutation<RegisterResponse, RegisterRequest>({
      query: (userInfo) => ({
        /**
         * Defines https request details
         * endpoint URL
         * HTTP method
         * Request body contains
         */
        url: "auth/register",
        method: "POST",
        body: userInfo,
      }),
      invalidatesTags: ["User"], // Invalidate "User" tag type after registration
    }),
  }),
});

// Export various hooks generated by the API instance for querying and mutating data
export const {
  useGetKpisQuery,
  useGetProductsQuery,
  useGetTransactionsQuery,
  useLoginMutation,
  useRegisterMutation,
} = api;
